# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-13 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20170127_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='background',
            field=models.ImageField(blank=True, upload_to=question.models.upload_location),
        ),
        migrations.AddField(
            model_name='question',
            name='story',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
