# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-26 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20180114_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='css',
            field=models.FileField(blank=True, upload_to=question.models.upload_location),
        ),
    ]
